<% project_name = 'full_stack_project_rails_api' %>

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: full_stack_project_rails_api_development

test:
  <<: *default
  database: full_stack_project_rails_api_test
